version: '3.1'

services:
  demo_db:
    container_name: demo-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: '@Bound4chegs'
      MYSQL_DATABASE: players_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql

#  demo_adminer:
#    container_name: demo-admin
#    image: adminer
#    restart: on-failure
#    ports:
#      - "9090:8080"

  demo_app:
    container_name: demo-app
    image: demo-app
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - demo_db
    environment:
      MYSQL_HOST: demo-db

volumes:
  db: