auth0:
  audience: http://players.demo/
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-octacore.us.auth0.com/
          jwk-set-uri: https://dev-octacore.us.auth0.com/.well-known/jwks.json